### ISSUE TITLE
Problems with catkin_make involving CMAKE_CXX_FLAGS

### ISSUE THREAD

**Issue by jo80923** [MISTLab/ROSBuzz#3]
In CMakeLists.txt the following line seems to be ignored by catkin_make when following tutorial in readme:

"""set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DSIMULATION=${SIM} -DMAVROSKINETIC=${KIN}")"""

Compilation errors occur in mavrosCC.h due to MAVROSKINETIC regarding incorrect mavros msgs.

ROS distro being used is Kinetic

**Comment by vivek-shankar** [comment]
Hai!
Thank you for your interest in ROSBuzz. 
The problem is that a flag "-DKIN=1" has to be passed along with catkin_make to specify the ROS version of mavros. For instance, you could compile with the following command "catkin_make -DSIM=1 -DKIN=1"
I will update the readme to include all the available flags and the necessary flags to be set.

**Comment by piepieninja** [comment]
having a similar problem. will attempt soon your solution soon.

**Comment by vivek-shankar** [comment]
I think this will solve the issue, let me know how it goes.

**Comment by jo80923** [comment]
This worked. Thank you!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vivek-shankar** [comment]
If you run into any other issue, please feel free to report it. We will try to fix it as soon as possible.
