### ISSUE TITLE
A drone becomes invisible whenever broadcasting an "array of tables" structure

### ISSUE THREAD

**Issue by mmitjansc** [MISTLab/ROSBuzz#6]
Dear developers,

I have been working on a drone application using ROSBuzz for a few weeks, and so far it has been very intuitive and useful!

For a few days I have been facing an issue that could well be a bug in my implementation, but it also made me wonder whether there might a bug inside ROSBuzz itself. Below there is a summary of my application and the issue I'm facing:

**Context**: In simulation, I'm flying 3 different drones under one same swarm, each following different sets of waypoints. Each instance of rosbuzz simulating each drone runs in an independent Virtual Machine.
One specific drone (Drone A)  stores specific waypoints (between 3 and 5) during its mission under an _array of tables_ structure, which represents a matrix: each "array index" corresponds to a waypoint index, and each waypoint table contains 3 elements which are latitude, longitude and altitude.

**Goal:** When Drone A finishes its trajectory, it broadcasts via `neighbors.broadcast()` the saved data structure with waypoints to the other 2 drones (B and C). Then, B and C should receive it via `neighbors.listen()`, and follow them in a second mission.

**Issue**: Whenever the script in Drone A reaches the line that makes it broadcast this saved data structure, it seems like Drone A immediately "becomes invisible" to the other drones: this means that B and C never receive the broadcasted waypoint data structure from A, and at the same time they stop receiving other flight updates coming from A that are being broadcasted periodically throughout the entire simulation. The scripts in the 3 drones keep running smoothly, they don't throw any exception.

I tried modifying that line in Drone A's script to broadcast just dummy data (like integers, floats or even a simple dummy table), and in these cases all the other drones receive this data. But whenever I switch back to sending an _array of tables_, the rosbuzz connection drops.

Do you have any idea/suggestion on what might be happening? Thank you!

**Comment by beltrame** [comment]
Thank you for your interest in ROSBuzz. The easiest way for us to understand what is going on is if you can provide a minimal script that causes the issue, so that we can try to replicate it.

**Comment by mmitjansc** [comment]
Thank you for your fast reply. 

Attached is a minimal script to use between 2 drones, with ID's 1 and 2. Drone 1 broadcasts a constant message in its `step()` function that Drone 2 listens to. Additionally, once Drone 1 enters the ACTION state (after TAKEOFF ends), it also broadcasts a dummy array of tables for Drone 2. With the log of the messages, it can be seen that Drone 2 never receives this array broadcast, and additionally stops receiving the constant message broadcasted by Drone 1 in the `step()` function.

[test_script.txt](https://github.com/MISTLab/ROSBuzz/files/6747715/test_script.txt)

This is the log of Drone 2:
![image](https://user-images.githubusercontent.com/56123749/124117056-a91c5a80-da3d-11eb-9337-3abb850094aa.png)

**Comment by vivek-shankar** [comment]
Hai, 
Thank you for your interest in ROSBuzz. 
I looked into your issue, the problem here is that inside ROSBuzz there is a constant that defines the MAX message size. 
If you are using more broadcasts and other constructs like Virtual Stigmergy, in the background ROSBuzz has to broadcast more information to be able to transfer all the information. The Buzz Virtual Machine has ways to prioritize messages and send only what can be sent. In your case, the msg size is smaller than that of one single message (neighbors.broadcast), which would ideally be clogging the queue, hence it was remove all together from the queue and other data transfer from other constructs like virtual stigmergy is kept to be flowing.  
The message size that we have is 190 bytes, it was adapted to the Xbee payload size. If you are using WIFI or other communication infrastructure allowing large transfer, you could increase it. 
The constant is declared here: https://github.com/MISTLab/ROSBuzz/blob/master/src/buzz_utility.cpp#L20
Feel free to change it to fit your needs, I changed it to 500 bytes and I was able to send 7 table entries. Increase it further, if you want more. 
In the future, I will make this parameter a launch file argument. I am currently a bit busy, will do this in a couple of weeks. 
Until then please change this parameter in the location I indicated to fit your need.

With best regards,
Vivek

**Comment by mmitjansc** [comment]
Hi Vivek,

That completely solved the issue, thank you! 

If we end up using Xbees on the real drones we'll definitely have to take into account this constraint. I'll think of a more efficient way to broadcast this information between drones.

Thanks again, and best regards,
Marc
